version: "3.3"

services:
  app-database:
    image: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
      POSTGRES_DB: CurrencyConverted
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - app-database

  frontend:
    image: atanasls/front-end-currency-final:latest
    depends_on:
      - currency-conversion-api
    ports:
      - 4201:4200
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  currency-conversion-api:
    image: atanasls/currency-converter-api
    depends_on:
      - app-database
    ports:
      - 5001:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --debug --http-api-update
      environment:
        - WATCHTOWER_HTTP_API_TOKEN=mytoken
        - WATCHTOWER_LABEL_ENABLE=true
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      ports:
        - 8081:8080
    
  
  


 